### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [72]:
#Declare the function
def take_str(c,a,b):  
    s = c[a:b]
    l = len(s)
    return (s , l)

c = input('entrer la chaine ')
a = int(input('give the value '))
b = int(input('enter the value '))
#Call the function
take_str(c,a,b)
sl = take_str(c,a,b)[0]
lg = take_str(c,a,b)[1]
#print the result in a well formated format
print('{0} et {1}'.format(sl, lg))

entrer la chaine hgggggggggrhi
give the value 4
enter the value 2
 et 0


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [73]:
#Declare the function
def somme(a,b):
    s = a+b
    return s
#Call with the values 1 and two
a = 1
b =2.1
c =False
d =2
print(somme(a,b))
print(somme(c,d))
#Check the type of the result
print(type(somme(a,b)))
print(type(somme(c,d)))


3.1
2
<class 'float'>
<class 'int'>


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [30]:
#Declare the function
#dic = {'key':1,'key1':2}
#print(dic['key1'])


def take_st(ch):
    d = {q:ch.count(q) for q in ch}
    return d

ch = 'test'
#Print the result
print(take_st(ch))
#...

{'t': 2, 'e': 1, 's': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [1]:
l1 = [1,2,3,4,5,6,7,8,9,10]
l2 = [1,2,3,4,5,6,7,8,9,10]
def display_item(l1,l2):
    n = len(l2)
    for i in range(n):
        print(l1[i],(n-i-1))
            
display_item(l1,l2)

1 9
2 8
3 7
4 6
5 5
6 4
7 3
8 2
9 1
10 0


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [41]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2,-1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print(a)
print(b)
#concatenate horizontally
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])
new_data = np.concatenate((a,b),axis = 1)
new_data

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [14]:
import numpy as np
a = np.arange(3)
b = np.ones((3,3,3))
#print(a)
##print(b)
#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
#...
print('ouput1 : \n',np.append(np.repeat(a,3), np.tile(a,3))
)
#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])


#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

ouput1 : 
 [0 0 0 1 1 1 2 2 2 0 1 2 0 1 2 0 1 2]
